version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:15.5-alpine3.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/data/postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres: