run:
    uvicorn patient_backend.main:app --host 0.0.0.0 --port 8000 --reload

lint:
    black .
    flake8 .

test:
    pytest tests/

docker-build:
    docker build -t /patient_backend .

docker-run:
    docker-compose up

docker-stop:
    docker-compose down